# Generated by Django 4.0.2 on 2024-03-12 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='id_producto',
            field=models.ManyToManyField(through='Project.DetalleSolicitud', to='Project.Producto', verbose_name='Producto'),
        ),
    ]
